### ISSUE TITLE
Exec<...>.Output does not preserve newlines in output

### ISSUE THREAD

**Issue by bent-rasmussen** [Tarmil/FSharp.Data.LiteralProviders#22]
I love this library (just discovered it)! I can now get rid of some hacky MSBUILD stuff.

However, it seems the `Exec` `Output` property does not maintain newlines. I guess this is because the code uses `StringBuilder.Append` rather than `StringBuilder.AppendLine`:

https://github.com/Tarmil/FSharp.Data.LiteralProviders/blob/2c51a16429eae1f7f8417eac184eb7cbf5670c65/src/FSharp.Data.LiteralProviders.DesignTime/Exec.fs#L55

I have a use case like this:

```fsharp
let [<Literal>] PendingChanges = Exec<"git", "diff HEAD --name-only">.Output
```

Filenames are then concatenated into an alphabet soup.  🙂

**Comment by Tarmil** [comment]
That's definitely a problem.

I don't think just replacing `Append` with `AppendLine` is the right solution though; for example, if there's only one line, we don't want to add a final newline. I think the right way to do it is to add a newline at the start unless this is the first line.
