### ISSUE TITLE
Feature request: fully qualified nameof

### ISSUE THREAD

**Issue by nodakai** [Tarmil/FSharp.Data.LiteralProviders#27]
Background: https://stackoverflow.com/a/40856014/

The proposed trick only applies to C# (whose "constant expressions" include concatenations like `nameof(Namespace) + "." + nameof(Namespace.Class)`)
Sadly we can't do the same with F# when you want some fully qualified type name to feed to _e.g._ `[<assembly:AutoOpen(...)>]`

If it's straightforward to add such a functionality to your Literal Providers suite, it would be awesome.

**Comment by Tarmil** [comment]
That would be useful, but unfortunately that is not possible with a type provider either. The TP receives its static parameters as already resolved values, it can't inspect the expression.

**Comment by nodakai** [comment]
Hmm right, I think I had some confusions on how `typeof` is implemented vs `nameof`, restrictions on TP parameters, and so on. Sorry for the noise.
